# Generated by Django 3.2.7 on 2021-09-16 10:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Department_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_department_name', models.CharField(max_length=200, verbose_name='แผนก')),
            ],
            options={
                'db_table': 'leaveapp_leave_department_create',
            },
        ),
        migrations.CreateModel(
            name='Leave_Type_Create',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type_name', models.CharField(max_length=200, verbose_name='ประเภทการลา')),
                ('leave_amount', models.PositiveIntegerField(verbose_name='จำนวนวันลา')),
            ],
            options={
                'db_table': 'leaveapp_leave_type_create',
            },
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(verbose_name='รหัสพนักงาน')),
                ('leave_reason', models.CharField(max_length=200)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('leave_amount', models.IntegerField(verbose_name='จำนวนวันลา')),
                ('upload', models.FileField(upload_to='file_uploads')),
                ('leave_contact', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'รออนุมัติ'), ('APPROVE', 'อนุมัติ'), ('REJECT', 'ไม่อนุมัติ')], default='รออนุมัติ', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('leave_department_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.leave_department_create')),
                ('leave_type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.leave_type_create')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaveapp_leave',
            },
        ),
    ]
