# Generated by Django 3.2.7 on 2021-09-17 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaveapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='ถึงวันที่'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_contact',
            field=models.CharField(max_length=200, verbose_name='การติดต่อระหว่างลา'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_department_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.leave_department_create', verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_reason',
            field=models.CharField(max_length=200, verbose_name='เหตุผลการลา'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveapp.leave_type_create', verbose_name='ประเภทการลา'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='ตั้งแต่วันที่'),
        ),
        migrations.AlterField(
            model_name='leave_department_create',
            name='leave_department_name',
            field=models.CharField(max_length=200),
        ),
    ]
